### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by OskarKlintrot** [RebeccaFransson/1dv450-rf222cz#1]
There would be very helpful with a vagrant box ie to use for development. RoR is a pain to install on Windows and also the version on Rails might be different on the local OS than the one this project uses. Also, Rails is already specified in the Gemfile so no need to install Rails on beforehand. 

When using a vagrant box (I'm using RoR dev box) I couldn't install some gems. It turned out that the gems is only used for production anyway so using `$ bundle install --without production` worked. It might be a good idea to mention this in the docs, no need to install gems for production when doing development and vice verse.

Using `$ rake db:migrate` is bad practice when creating the application on another system, then `$ rake db:schema:load` should be used. See more in the comments of `db/schema.rb`.

Lastly when it comes to the installation for local development, `seeds.db` is more or less empty and dosen't even contain the credentials mentioned in the readme (it says it is supposed to add two user while in reality it only adds the admin user).

**Comment by RebeccaFransson** [comment]
Thank you, the readme-file is updated.

**Comment by OskarKlintrot** [comment]
:+1:

**Comment by 1dv450** [comment]
Great feedback through all the issues!
