### ISSUE TITLE
Possible to delete others API-keys

### ISSUE THREAD

**Issue by OskarKlintrot** [RebeccaFransson/1dv450-rf222cz#8]
There is no validation that the user is authorized to delete keys. Using the link `http://localhost:8080/removeApp.1` to remove the key with id 1, even though I where not logged in on the right account.

**Comment by RebeccaFransson** [comment]
Förstår inte vad du menar, fungerar inte på min applikation.

**Comment by OskarKlintrot** [comment]
Open the application in two different browsers (or use incognito mode in Chrome) and log in with two different users. Then copy the link for deleting an app in one of the browsers, paste it into the other and press enter. Since you are logged in it will delete the key, the validation only makes sure that you are logged in, not that you are admin or trying to remove your own keys.

You also might want to consider not closing an issue before it is solved :smile:

**Comment by RebeccaFransson** [comment]
Oh, sorry didnt mean to close it! its now fixed!
